# site setup
# Exclude this stuff
exclude: [node_modules, gulpfile.js, README.md, BUILD.md, LICENSE, .gitignore, pages, assets]
permalink: /:title/
markdown: kramdown
baseurl:
# course setup
title: "Statistical Methods for High-throughput Genomic Data I"
semester: "Fall 2017"
duration: "15 Weeks"
instructor:
 - Mikhail Dozmorov
coursecode:
 - "BIOS 567"
coursedates:
 - "Monday/Wednesday class: August 28 to December 6, 2017. No classes on September 4."
coursetime: "9:00 am to 10:20 am"
courselocation:
 - "Monday/Wednesday: One Capitol Square, Rm 5009"
communication:
 -
   name: "Email"
   description: ""
   details: "mikhail.dozmorov@vcuhealth.org"
 -
   name: ""
   description: ""
   details: ""
 -
   name: ""
   description: ""
   details: ""
officehours:
  description: "Monday/Wednesday 10:30 pm to 12:00 pm at Biostatistics Office 730."
  link: ""
# Tachyons Version
tv: "4.6.1"

# SCSS Compress
sass:
  style: compressed

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"

BASE_PATH : http://mdozmorov.github.io/BIOS567